### ISSUE TITLE
trouble building

### ISSUE THREAD

**Issue by benschw** [lusis/go-rundeck#1]
Can you point me in the right direction for building this project? I'm unfamiliar with your method of pulling in the rundeck.v12 package:

    $ go get github.com/lusis/go-rundeck
    $ cd $GOPATH/src/github.com/lusis/go-rundeck
    $ make all
    can't load package: package rundeck.v12: cannot find package "rundeck.v12" in any of:
            /usr/local/go/src/rundeck.v12 (from $GOROOT)
            /home/ben/go/src/rundeck.v12 (from $GOPATH)
    make: *** [test] Error 1
    $ go get ./...
    package rundeck.v12: unrecognized import path "rundeck.v12"
    $ go version
    go version go1.4.2 linux/amd64

**Comment by paulhamby** [comment]
I found that if I added the project root to my $GOPATH variable, I was able to build it.

i.e.
`cd go-rundeck`
``export GOPATH=$GOPATH:`pwd` ``

**Comment by benschw** [comment]
thanks!
